# a cron job that runs every 24 hours to keep the workflow alive
name: Keep Supabase Project Alive

on:
  schedule:
    - cron: "* * * * *"

jobs:
  keep-alive:
    runs-on: ubuntu-22.04
    steps:
      - run: curl https://life-in-weeks-xi.vercel.app/keep-alive
